/*
===============================================================================
           ___ ___         __                   
   .-----.|   |   |.-----.|  |.--.--.-----.----.
   |  -__||   |   ||  _  ||  ||  |  |  -__|   _|
   |_____| \_____/ |_____||__| \___/|_____|__|  
                                                  
   eVolver - protein sequence generator

   Computational Systems Biology Group
   Department of Biological Sciences
   Center for Computation & Technology
   Louisiana State University
   407 Choppin Hall, Baton Rouge, LA 70803, USA

   http://www.brylinski.org

   Report bugs to michal@brylinski.org

   Copyright 2013 Michal Brylinski

   This file is part of eVolver.

   eVolver is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
   (at your option) any later version.

   eVolver is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with eVolver. If not, see <http://www.gnu.org/licenses/>.

===============================================================================
*/


#include "output.h"

using namespace std;

void out_fasta( std::string fas_name, int fin_seq[], double fin_score )
{
 ofstream outfas( fas_name.c_str() );
 
 outfas << ">evolver " << res << " " << fin_score << endl;
 
 int i = 0;
 
 for ( int j = 0; j < res; j++ )
 {
  outfas << number2one(fin_seq[j]);
  
  if ( ++i >= 70 )
  {
   outfas << endl;
   
   i = 0;
  }
 }
 
 if ( i > 0 )
  outfas << endl;
 
 outfas.close();
}

void out_pdb( std::string pdb_name, int fin_seq[], double fin_score )
{
 ofstream outpdb( pdb_name.c_str() );
 
 outpdb << "REMARK Sequence generated by evolver" << endl
        << "REMARK Final score: " << fin_score << endl;
 
 for ( unsigned int i = 0; i < pdbcontent.size(); i++ )
 {
  pdbcontent[i].replace( 17, 3, number2three( fin_seq[atoi(pdbcontent[i].substr(22,4).c_str())-1] ) );
  
  outpdb << pdbcontent[i] << endl;
 }
 
 outpdb << "TER" << endl << "END" << endl;
 
 outpdb.close();
}
